# Generated by Django 4.2.7 on 2024-10-18 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_stocknews_delete_stockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknews',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
