# Generated by Django 4.2.7 on 2024-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_metadata_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='close_price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='high_price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='low_price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='open_price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
