name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and push Docker Image to DockerHub
      run: |
        docker build -t muasya1/financial-backend .
        docker login -u  ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
        docker push muasya1/financial-backend:latest
    
    - name: Deploy to Render
      uses: gh-actions-workflows/deploy-docker-render@v1.1
      with:
        deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
        image-url: muasya1/financial-backend:latest
        

#        use run| docker build -t `image_name` . docker login -u  'username' -p 'password' docker.io/ docker push `image_name`

      
